// Supabase Edge Function — create-invite
// POST { connection_type, custom_permissions? }
// Returns { invite_url, token }
// Used by mobile app; web app uses the Next.js server action directly.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { corsHeaders, handleCors } from '../_shared/cors.ts';

type ConnectionType = 'partner' | 'trainer' | 'ironmind' | 'friend';

const DEFAULT_PERMISSIONS: Record<ConnectionType, Record<string, boolean>> = {
  partner: {
    phase_name: true,
    energy_mood: true,
    support_cues: true,
    forecast: true,
    cycle_dates: false,   // always false — exact dates never exposed
    symptoms: false,      // always false
    health_data: false,   // always false
  },
  trainer: {
    phase_name: true,
    training_recs: true,
    sleep_hrv: true,
    cycle_dates: false,
    emotional_data: false, // always false
    symptoms: false,       // always false
  },
  ironmind: {
    phase_name: true,
    gritscore_context: true,
    symptom_data: false,   // user decides
  },
  friend: {
    phase_name: true,
    energy_mood: true,
    forecast: false,
  },
};

// Keys that are locked off regardless of what the user passes
const ALWAYS_PRIVATE: Record<ConnectionType, string[]> = {
  partner: ['cycle_dates', 'symptoms', 'health_data'],
  trainer: ['cycle_dates', 'emotional_data', 'symptoms'],
  ironmind: [],
  friend: [],
};

interface RequestBody {
  connection_type: ConnectionType;
  custom_permissions?: Record<string, boolean>;
}

Deno.serve(async (req: Request) => {
  const corsResponse = handleCors(req);
  if (corsResponse) return corsResponse;

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const appUrl = Deno.env.get('APP_URL') ?? 'https://herside.app';

  const authHeader = req.headers.get('Authorization');
  if (!authHeader) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401, headers: { ...corsHeaders, 'content-type': 'application/json' },
    });
  }

  const supabase = createClient(supabaseUrl, supabaseKey);
  const { data: { user }, error: authErr } = await supabase.auth.getUser(
    authHeader.replace('Bearer ', ''),
  );
  if (authErr || !user) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401, headers: { ...corsHeaders, 'content-type': 'application/json' },
    });
  }

  let body: RequestBody;
  try { body = await req.json(); }
  catch { return new Response(JSON.stringify({ error: 'Invalid JSON' }), { status: 400, headers: { ...corsHeaders, 'content-type': 'application/json' } }); }

  const { connection_type, custom_permissions = {} } = body;
  if (!DEFAULT_PERMISSIONS[connection_type]) {
    return new Response(JSON.stringify({ error: 'Invalid connection_type' }), {
      status: 400, headers: { ...corsHeaders, 'content-type': 'application/json' },
    });
  }

  // Merge defaults with custom, then enforce always-private locks
  const permissions = { ...DEFAULT_PERMISSIONS[connection_type], ...custom_permissions };
  for (const key of ALWAYS_PRIVATE[connection_type]) {
    permissions[key] = false;
  }

  try {
    // 1. Create connection record (invite_token auto-generated by DB)
    const { data: connection, error: connErr } = await supabase
      .from('circle_connections')
      .insert({
        her_user_id: user.id,
        connection_type,
        status: 'pending',
        invite_expires_at: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      })
      .select('id, invite_token')
      .single();

    if (connErr || !connection) throw connErr ?? new Error('Failed to create connection');

    // 2. Insert permission rows in bulk
    const { error: permErr } = await supabase.from('privacy_permissions').insert(
      Object.entries(permissions).map(([key, enabled]) => ({
        connection_id: connection.id,
        permission_key: key,
        enabled,
      })),
    );
    if (permErr) throw permErr;

    const inviteUrl = `${appUrl}/invite/${connection.invite_token}`;

    return new Response(JSON.stringify({ invite_url: inviteUrl, token: connection.invite_token }), {
      headers: { ...corsHeaders, 'content-type': 'application/json' },
    });
  } catch (err) {
    console.error('create-invite error:', err);
    return new Response(JSON.stringify({ error: 'Failed to create invite' }), {
      status: 500, headers: { ...corsHeaders, 'content-type': 'application/json' },
    });
  }
});
